### ISSUE TITLE
Design better wording for issues in tasklist

### ISSUE THREAD

**Issue by alextea** [digital-land/provider-design-sprint#6]
## What

When issues appear in the tasklist we need to ensure the wording is clear and understandable by users.

The issues are grouped by issue type.

Issues might affect a whole dataset (eg a missing column, missing values in an entire column or invalid data in an entire column) or they might affect individual rows. 

A dataset might have multiple different types of issues. 

## Problem statement

LPAs need to know what issues they need to fix in their datasets

## User stories

As an LPA
I need to know what issues exist in my dataset
So I can understand what I need to do to improve my dataset

As an LPA
I need to know how many rows and fields are affected by issues
So I know how many problems there are

## Known Artefacts

I have extracted all the issue types from the database here:
https://docs.google.com/spreadsheets/d/1hvffB4LuHEHR2WutAxp98CzG0WsZJFlx-2VmGeIM5Yk/edit?gid=813787384#gid=813787384

### Current Design

![Image](https://github.com/user-attachments/assets/3e14856e-8af3-4343-9785-eb5e4471d11d)

https://design-sprint-prototype-8e5ca5d98540.herokuapp.com/overview/v2/local-authority:LBH/dataset/listed-building-outline/tasklist

## Linked Tasks

**Comment by GeorgeGoodall** [comment]
a technical question we have around these messages is how we store them. I've opened another Spike ticket to address this. probably something for infa to look at (though i have proposed a solution as a starting point on the ticket)

https://github.com/orgs/digital-land/projects/7/views/4?pane=issue&itemId=73679244
